
server:
  port: 8088
spring:
  application:
    name: cloud-gateway-demo
  cloud:
    gateway:
      routes:
        - id: data-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/data/**