
server:
  port: 8088

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/userInfo/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accountInfo/**